project_id = "qqmcwxfhdlzwxsfdxsfg"

[functions.rate-limit]
verify_jwt = false

[functions.send-transaction-email]
verify_jwt = false

[functions.send-critical-event-email]
verify_jwt = false

[functions.send-activity-report]
verify_jwt = false

[functions.scheduled-reports-cron]
verify_jwt = false
